
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TrainContractArtifactJson from './artifacts/Train.json' with { type: 'json' };
export const TrainContractArtifact = loadContractArtifact(TrainContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Train;
 */
export class TrainContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, TrainContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, TrainContract.artifact, wallet) as Promise<TrainContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<TrainContract>(PublicKeys.default(), wallet, TrainContractArtifact, TrainContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<TrainContract>(publicKeys, wallet, TrainContractArtifact, TrainContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TrainContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TrainContract['methods'][M]>
  ) {
    return new DeployMethod<TrainContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TrainContractArtifact,
      TrainContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TrainContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TrainContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'contracts' | 'user_swaps_count' | 'user_swaps'> {
      return {
        contracts: {
      slot: new Fr(1n),
    },
user_swaps_count: {
      slot: new Fr(2n),
    },
user_swaps: {
      slot: new Fr(3n),
    }
      } as ContractStorageLayout<'contracts' | 'user_swaps_count' | 'user_swaps'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_htlc(swap_id: field, htlc_id: field) */
    get_htlc: ((swap_id: FieldLike, htlc_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_user_swaps_count(user: struct) */
    get_user_swaps_count: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_htlc(swap_id: field, htlc_id: field) */
    has_htlc: ((swap_id: FieldLike, htlc_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** lock_dst(swap_id: field, htlc_id: field, hashlock_high: integer, hashlock_low: integer, reward: integer, reward_timelock: integer, timelock: integer, src_receiver: struct, token: struct, total_amount: integer, src_asset: string, dst_chain: string, dst_asset: string, dst_address: string) */
    lock_dst: ((swap_id: FieldLike, htlc_id: FieldLike, hashlock_high: (bigint | number), hashlock_low: (bigint | number), reward: (bigint | number), reward_timelock: (bigint | number), timelock: (bigint | number), src_receiver: AztecAddressLike, token: AztecAddressLike, total_amount: (bigint | number), src_asset: string, dst_chain: string, dst_asset: string, dst_address: string) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** lock_src(swap_id: field, hashlock_high: integer, hashlock_low: integer, timelock: integer, src_receiver: struct, token: struct, amount: integer, src_asset: string, dst_chain: string, dst_asset: string, dst_address: string) */
    lock_src: ((swap_id: FieldLike, hashlock_high: (bigint | number), hashlock_low: (bigint | number), timelock: (bigint | number), src_receiver: AztecAddressLike, token: AztecAddressLike, amount: (bigint | number), src_asset: string, dst_chain: string, dst_asset: string, dst_address: string) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** redeem(swap_id: field, htlc_id: field, secret_high: integer, secret_low: integer) */
    redeem: ((swap_id: FieldLike, htlc_id: FieldLike, secret_high: (bigint | number), secret_low: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refund(swap_id: field, htlc_id: field) */
    refund: ((swap_id: FieldLike, htlc_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
